# This file is auto-generated by bindings/generate_bindings.py.
# Do not edit by hand.
from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple


@dataclass(frozen=True)
class ScalarParam:
    name: str
    ctype: str
    default: str | None = None


@dataclass(frozen=True)
class FunctionSpec:
    c_name: str
    inputs: Tuple[str, ...]
    outputs: Tuple[str, ...]
    size_param: str
    scalars: Tuple[ScalarParam, ...]


FUNCTIONS = {
    "sma": FunctionSpec(
        c_name="ct_sma",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ma": FunctionSpec(
        c_name="ct_ma",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="type", ctype="ctMaType_t"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "wma": FunctionSpec(
        c_name="ct_wma",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "momentum": FunctionSpec(
        c_name="ct_momentum",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "change": FunctionSpec(
        c_name="ct_change",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "roc": FunctionSpec(
        c_name="ct_roc",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rocp": FunctionSpec(
        c_name="ct_rocp",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rocr": FunctionSpec(
        c_name="ct_rocr",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rocr100": FunctionSpec(
        c_name="ct_rocr100",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ema": FunctionSpec(
        c_name="ct_ema",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "dema": FunctionSpec(
        c_name="ct_dema",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "tema": FunctionSpec(
        c_name="ct_tema",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "t3": FunctionSpec(
        c_name="ct_t3",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="vFactor", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "trima": FunctionSpec(
        c_name="ct_trima",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "trix": FunctionSpec(
        c_name="ct_trix",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "max": FunctionSpec(
        c_name="ct_max",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "min": FunctionSpec(
        c_name="ct_min",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "maxindex": FunctionSpec(
        c_name="ct_maxindex",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "minindex": FunctionSpec(
        c_name="ct_minindex",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "minmax": FunctionSpec(
        c_name="ct_minmax",
        inputs=("host_input",),
        outputs=("host_min", "host_max"),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "minmaxindex": FunctionSpec(
        c_name="ct_minmaxindex",
        inputs=("host_input",),
        outputs=("host_minidx", "host_maxidx"),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "stddev": FunctionSpec(
        c_name="ct_stddev",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "var": FunctionSpec(
        c_name="ct_var",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "sum": FunctionSpec(
        c_name="ct_sum",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rsi": FunctionSpec(
        c_name="ct_rsi",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "kama": FunctionSpec(
        c_name="ct_kama",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "macd_line": FunctionSpec(
        c_name="ct_macd_line",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "macd": FunctionSpec(
        c_name="ct_macd",
        inputs=("host_input",),
        outputs=("host_macd", "host_signal", "host_hist"),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="signalPeriod", ctype="int"),
            ScalarParam(name="type", ctype="ctMaType_t"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "macdfix": FunctionSpec(
        c_name="ct_macdfix",
        inputs=("host_input",),
        outputs=("host_macd", "host_signal", "host_hist"),
        size_param="size",
        scalars=(
            ScalarParam(name="signalPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "mama": FunctionSpec(
        c_name="ct_mama",
        inputs=("host_input",),
        outputs=("host_mama", "host_fama"),
        size_param="size",
        scalars=(
            ScalarParam(name="fastLimit", ctype="float"),
            ScalarParam(name="slowLimit", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "apo": FunctionSpec(
        c_name="ct_apo",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ppo": FunctionSpec(
        c_name="ct_ppo",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "pvo": FunctionSpec(
        c_name="ct_pvo",
        inputs=("host_volume",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "sma_device": FunctionSpec(
        c_name="ct_sma_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ma_device": FunctionSpec(
        c_name="ct_ma_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="type", ctype="ctMaType_t"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "wma_device": FunctionSpec(
        c_name="ct_wma_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "momentum_device": FunctionSpec(
        c_name="ct_momentum_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "change_device": FunctionSpec(
        c_name="ct_change_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "roc_device": FunctionSpec(
        c_name="ct_roc_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rocp_device": FunctionSpec(
        c_name="ct_rocp_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rocr_device": FunctionSpec(
        c_name="ct_rocr_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rocr100_device": FunctionSpec(
        c_name="ct_rocr100_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ema_device": FunctionSpec(
        c_name="ct_ema_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "dema_device": FunctionSpec(
        c_name="ct_dema_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "tema_device": FunctionSpec(
        c_name="ct_tema_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "t3_device": FunctionSpec(
        c_name="ct_t3_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="vFactor", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "trima_device": FunctionSpec(
        c_name="ct_trima_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "trix_device": FunctionSpec(
        c_name="ct_trix_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "max_device": FunctionSpec(
        c_name="ct_max_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "min_device": FunctionSpec(
        c_name="ct_min_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "maxindex_device": FunctionSpec(
        c_name="ct_maxindex_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "minindex_device": FunctionSpec(
        c_name="ct_minindex_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "stddev_device": FunctionSpec(
        c_name="ct_stddev_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "var_device": FunctionSpec(
        c_name="ct_var_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "sum_device": FunctionSpec(
        c_name="ct_sum_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "rsi_device": FunctionSpec(
        c_name="ct_rsi_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "kama_device": FunctionSpec(
        c_name="ct_kama_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "macd_line_device": FunctionSpec(
        c_name="ct_macd_line_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "apo_device": FunctionSpec(
        c_name="ct_apo_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ppo_device": FunctionSpec(
        c_name="ct_ppo_device",
        inputs=("device_input",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "pvo_device": FunctionSpec(
        c_name="ct_pvo_device",
        inputs=("device_volume",),
        outputs=("device_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="fastPeriod", ctype="int"),
            ScalarParam(name="slowPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "bbands": FunctionSpec(
        c_name="ct_bbands",
        inputs=("host_input",),
        outputs=("host_upper", "host_middle", "host_lower"),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="upperMul", ctype="float"),
            ScalarParam(name="lowerMul", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "atr": FunctionSpec(
        c_name="ct_atr",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="initial", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "natr": FunctionSpec(
        c_name="ct_natr",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "trange": FunctionSpec(
        c_name="ct_trange",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "stochastic": FunctionSpec(
        c_name="ct_stochastic",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_k", "host_d"),
        size_param="size",
        scalars=(
            ScalarParam(name="kPeriod", ctype="int"),
            ScalarParam(name="dPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "stochf": FunctionSpec(
        c_name="ct_stochf",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_k", "host_d"),
        size_param="size",
        scalars=(
            ScalarParam(name="kPeriod", ctype="int"),
            ScalarParam(name="dPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "stochrsi": FunctionSpec(
        c_name="ct_stochrsi",
        inputs=("host_input",),
        outputs=("host_k", "host_d"),
        size_param="size",
        scalars=(
            ScalarParam(name="rsiPeriod", ctype="int"),
            ScalarParam(name="kPeriod", ctype="int"),
            ScalarParam(name="dPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cci": FunctionSpec(
        c_name="ct_cci",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "adx": FunctionSpec(
        c_name="ct_adx",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "adxr": FunctionSpec(
        c_name="ct_adxr",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "plus_dm": FunctionSpec(
        c_name="ct_plus_dm",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "minus_dm": FunctionSpec(
        c_name="ct_minus_dm",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "plus_di": FunctionSpec(
        c_name="ct_plus_di",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "minus_di": FunctionSpec(
        c_name="ct_minus_di",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "mfi": FunctionSpec(
        c_name="ct_mfi",
        inputs=("host_high", "host_low", "host_close", "host_volume"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "obv": FunctionSpec(
        c_name="ct_obv",
        inputs=("host_price", "host_volume"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "sar": FunctionSpec(
        c_name="ct_sar",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="step", ctype="float"),
            ScalarParam(name="maxAcceleration", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "sarext": FunctionSpec(
        c_name="ct_sarext",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="startValue", ctype="float"),
            ScalarParam(name="offsetOnReverse", ctype="float"),
            ScalarParam(name="accInitLong", ctype="float"),
            ScalarParam(name="accLong", ctype="float"),
            ScalarParam(name="accMaxLong", ctype="float"),
            ScalarParam(name="accInitShort", ctype="float"),
            ScalarParam(name="accShort", ctype="float"),
            ScalarParam(name="accMaxShort", ctype="float"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "aroon": FunctionSpec(
        c_name="ct_aroon",
        inputs=("host_high", "host_low"),
        outputs=("host_up", "host_down", "host_osc"),
        size_param="size",
        scalars=(
            ScalarParam(name="upPeriod", ctype="int"),
            ScalarParam(name="downPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "aroonosc": FunctionSpec(
        c_name="ct_aroonosc",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "adosc": FunctionSpec(
        c_name="ct_adosc",
        inputs=("host_high", "host_low", "host_close", "host_volume"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="shortPeriod", ctype="int"),
            ScalarParam(name="longPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ultosc": FunctionSpec(
        c_name="ct_ultosc",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="shortPeriod", ctype="int"),
            ScalarParam(name="mediumPeriod", ctype="int"),
            ScalarParam(name="longPeriod", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ad": FunctionSpec(
        c_name="ct_ad",
        inputs=("host_high", "host_low", "host_close", "host_volume"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "avgprice": FunctionSpec(
        c_name="ct_avgprice",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "medprice": FunctionSpec(
        c_name="ct_medprice",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "typprice": FunctionSpec(
        c_name="ct_typprice",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "wclprice": FunctionSpec(
        c_name="ct_wclprice",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "willr": FunctionSpec(
        c_name="ct_willr",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "midpoint": FunctionSpec(
        c_name="ct_midpoint",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "midprice": FunctionSpec(
        c_name="ct_midprice",
        inputs=("host_high", "host_low"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "beta": FunctionSpec(
        c_name="ct_beta",
        inputs=("host_x", "host_y"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "bop": FunctionSpec(
        c_name="ct_bop",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_doji": FunctionSpec(
        c_name="ct_cdl_doji",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_hammer": FunctionSpec(
        c_name="ct_cdl_hammer",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_inverted_hammer": FunctionSpec(
        c_name="ct_cdl_inverted_hammer",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_bullish_engulfing": FunctionSpec(
        c_name="ct_cdl_bullish_engulfing",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_bearish_engulfing": FunctionSpec(
        c_name="ct_cdl_bearish_engulfing",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_three_white_soldiers": FunctionSpec(
        c_name="ct_cdl_three_white_soldiers",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_abandoned_baby": FunctionSpec(
        c_name="ct_cdl_abandoned_baby",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_advance_block": FunctionSpec(
        c_name="ct_cdl_advance_block",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_belt_hold": FunctionSpec(
        c_name="ct_cdl_belt_hold",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_breakaway": FunctionSpec(
        c_name="ct_cdl_breakaway",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_two_crows": FunctionSpec(
        c_name="ct_cdl_two_crows",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_three_black_crows": FunctionSpec(
        c_name="ct_cdl_three_black_crows",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_three_inside": FunctionSpec(
        c_name="ct_cdl_three_inside",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_three_line_strike": FunctionSpec(
        c_name="ct_cdl_three_line_strike",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_three_stars_in_south": FunctionSpec(
        c_name="ct_cdl_three_stars_in_south",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_closing_marubozu": FunctionSpec(
        c_name="ct_cdl_closing_marubozu",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_conceal_baby_swallow": FunctionSpec(
        c_name="ct_cdl_conceal_baby_swallow",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_counterattack": FunctionSpec(
        c_name="ct_cdl_counterattack",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_dark_cloud_cover": FunctionSpec(
        c_name="ct_cdl_dark_cloud_cover",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_doji_star": FunctionSpec(
        c_name="ct_cdl_doji_star",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_dragonfly_doji": FunctionSpec(
        c_name="ct_cdl_dragonfly_doji",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_engulfing": FunctionSpec(
        c_name="ct_cdl_engulfing",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_evening_doji_star": FunctionSpec(
        c_name="ct_cdl_evening_doji_star",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_evening_star": FunctionSpec(
        c_name="ct_cdl_evening_star",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_gap_side_side_white": FunctionSpec(
        c_name="ct_cdl_gap_side_side_white",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_gravestone_doji": FunctionSpec(
        c_name="ct_cdl_gravestone_doji",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_hanging_man": FunctionSpec(
        c_name="ct_cdl_hanging_man",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_harami": FunctionSpec(
        c_name="ct_cdl_harami",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_harami_cross": FunctionSpec(
        c_name="ct_cdl_harami_cross",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_high_wave": FunctionSpec(
        c_name="ct_cdl_high_wave",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_hikkake": FunctionSpec(
        c_name="ct_cdl_hikkake",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_hikkake_mod": FunctionSpec(
        c_name="ct_cdl_hikkake_mod",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_homing_pigeon": FunctionSpec(
        c_name="ct_cdl_homing_pigeon",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_identical_three_crows": FunctionSpec(
        c_name="ct_cdl_identical_three_crows",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_in_neck": FunctionSpec(
        c_name="ct_cdl_in_neck",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_kicking": FunctionSpec(
        c_name="ct_cdl_kicking",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_kicking_by_length": FunctionSpec(
        c_name="ct_cdl_kicking_by_length",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_ladder_bottom": FunctionSpec(
        c_name="ct_cdl_ladder_bottom",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_long_legged_doji": FunctionSpec(
        c_name="ct_cdl_long_legged_doji",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_long_line": FunctionSpec(
        c_name="ct_cdl_long_line",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_marubozu": FunctionSpec(
        c_name="ct_cdl_marubozu",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_matching_low": FunctionSpec(
        c_name="ct_cdl_matching_low",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_mat_hold": FunctionSpec(
        c_name="ct_cdl_mat_hold",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_morning_doji_star": FunctionSpec(
        c_name="ct_cdl_morning_doji_star",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_morning_star": FunctionSpec(
        c_name="ct_cdl_morning_star",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_on_neck": FunctionSpec(
        c_name="ct_cdl_on_neck",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_piercing": FunctionSpec(
        c_name="ct_cdl_piercing",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_rickshaw_man": FunctionSpec(
        c_name="ct_cdl_rickshaw_man",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_rise_fall3_methods": FunctionSpec(
        c_name="ct_cdl_rise_fall3_methods",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_separating_lines": FunctionSpec(
        c_name="ct_cdl_separating_lines",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_shooting_star": FunctionSpec(
        c_name="ct_cdl_shooting_star",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_short_line": FunctionSpec(
        c_name="ct_cdl_short_line",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_spinning_top": FunctionSpec(
        c_name="ct_cdl_spinning_top",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_stalled_pattern": FunctionSpec(
        c_name="ct_cdl_stalled_pattern",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_stick_sandwich": FunctionSpec(
        c_name="ct_cdl_stick_sandwich",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_takuri": FunctionSpec(
        c_name="ct_cdl_takuri",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_tasuki_gap": FunctionSpec(
        c_name="ct_cdl_tasuki_gap",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_thrusting": FunctionSpec(
        c_name="ct_cdl_thrusting",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_tristar": FunctionSpec(
        c_name="ct_cdl_tristar",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_unique_3_river": FunctionSpec(
        c_name="ct_cdl_unique_3_river",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_upside_gap_2_crows": FunctionSpec(
        c_name="ct_cdl_upside_gap_2_crows",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cdl_xside_gap_3_methods": FunctionSpec(
        c_name="ct_cdl_xside_gap_3_methods",
        inputs=("host_open", "host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "cmo": FunctionSpec(
        c_name="ct_cmo",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "correl": FunctionSpec(
        c_name="ct_correl",
        inputs=("host_x", "host_y"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "dx": FunctionSpec(
        c_name="ct_dx",
        inputs=("host_high", "host_low", "host_close"),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "linearreg": FunctionSpec(
        c_name="ct_linearreg",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "linearreg_slope": FunctionSpec(
        c_name="ct_linearreg_slope",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "linearreg_intercept": FunctionSpec(
        c_name="ct_linearreg_intercept",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "linearreg_angle": FunctionSpec(
        c_name="ct_linearreg_angle",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "tsf": FunctionSpec(
        c_name="ct_tsf",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="period", ctype="int"),
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ht_dcperiod": FunctionSpec(
        c_name="ct_ht_dcperiod",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ht_dcphase": FunctionSpec(
        c_name="ct_ht_dcphase",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ht_phasor": FunctionSpec(
        c_name="ct_ht_phasor",
        inputs=("host_input",),
        outputs=("host_inphase", "host_quadrature"),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ht_sine": FunctionSpec(
        c_name="ct_ht_sine",
        inputs=("host_input",),
        outputs=("host_sine", "host_leadsine"),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ht_trendline": FunctionSpec(
        c_name="ct_ht_trendline",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
    "ht_trendmode": FunctionSpec(
        c_name="ct_ht_trendmode",
        inputs=("host_input",),
        outputs=("host_output",),
        size_param="size",
        scalars=(
            ScalarParam(name="stream", ctype="cudaStream_t", default="0"),
        ),
    ),
}

__all__ = tuple(sorted(FUNCTIONS))

